# SOURCE: https://docs.obsidian.md/Plugins/Releasing/Release+your+plugin+with+GitHub+Actions
name: Release Obsidian plugin

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: nightly
                  target: wasm32-unknown-unknown

            - name: Install wasm-pack
              run: bun install -g wasm-pack

            - name: Set Nightly
              run: cd wasm && rustup override set nightly && rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu && cd ..

            - name: Build plugin
              run: |
                  bun install
                  bun run wasm:test || exit 1
                  bun run wasm:build || exit 1
                  bun run test || exit 1
                  bun run build || exit 1

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"

                  gh release create "$tag" \
                    --title="$tag" \
                    --prerelease \
                    main.js manifest.json styles.css
